# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '17-PrimeiroProjetoViewCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 17-PrimeiroProjetoViewCode

pod 'SnapKit', '~> 5.6.0'

end
