# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '18-AppBackFront' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 18-AppBackFront

pod 'Alamofire'
pod 'AlamofireImage'

end
